apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zegreo-api
  namespace: zegreo-api
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.zogreo.online
      secretName: zegreo-api-tls
  rules:
    - host: api.zogreo.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zegreo-api
                port:
                  number: 80
